### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by gagarski** [flomikoon/Cut#1]
1. Не везде соблюдаются принятые в Джаве конвенции именования. Некоторые методы почему-то называются с большой буквы. Пакеты принято тоже именовать с маленькой буквы.
2. Разбор аргументов командной строки лучше бы вынести в отдельный класс, конструктор которого принимает массив `args`, а геттеры возвращают флаги. 
3. Вместо массива для range лучше тоже использовать класс с двумя полями.
4. Нужно ли хранить все обработанные строки? Нельзя ли обрабатывать ввод по одной строке и после записи в выходной поток забывать про неё?
5. Логика чтения из файла дублируется в двух ветках `if`а. Цикл чтения следует вынести за ветвление, оставив внутри только создание `reader`а.
6. Вывод можно организовать аналогично вводу, создавая разные `writer`ы.
7. https://github.com/flomikoon/Cut/blob/9520643864919750cd92f8ede3a9f54781a7e462/src/Main/Cut.java#L80-L82
Эту проверку следовало сделать раньше, и в случае, если флаги некорректны, завершить программу. Основную чать программы лучше вынести из ветвления (наверняка вам что-то такое писали в замечаниях в прошлом семестре).
8. https://github.com/flomikoon/Cut/blob/9520643864919750cd92f8ede3a9f54781a7e462/src/Main/Help.java#L73
По-моему, это не то, что требовалось в задании. Нужно было взять подстроку от N до конца, а не N последних символов. В методе со словами то же самое. 
9. Почему-то опять используете 0 как "особые" значения для N и K. Для N - 0 - это действительно значение по-умолчанию. Если K равно нулю - это формально пустой диапазон.  См также п. 3.
10. Не верю, что для разных ветвей в `lineC ` и `lineW` нужен настолько разный код. Попробуйте организовать логику так. В случае отсутствующих N или K вычислить их "правильные значения", а потом выполнить основную часть функции (например, в `lineC` - это `substring`)

**Comment by flomikoon** [comment]
Испраленно

**Comment by gagarski** [comment]
1. Зачем каждый раз создаёте новый объект `Pars`?
2. Логика для ввода и вывода всё ещё дублируется. В `if (new Pars(args).getO())` должно быть только создание `Scaner`'а. Из консоли, как и из файла слудует читать до конца, а не до пустой строки (то есть логика должна быть одинаковой). Конец файла в консоли - это нажатие Ctrl-D. Логику для вывода тоже следует сделать общей: можно сделать метод `writeStr`, который принимает `Writer`, в который он пишет, а создание и закрытие этого `Writer`а вынести наружу.
